[package]
name = "argoncrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
chacha20poly1305 = { version = "0.9.0", features = ["stream"] }
rand = "0.8.5"
rpassword = "7.3.1"
rust-argon2 = "2.1.0"
walkdir = "2.5.0"
zeroize = "1.8.1"
